# Generated by Django 5.0.14 on 2026-02-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="slug",
            field=models.SlugField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="servicecategory",
            constraint=models.UniqueConstraint(
                fields=("slug", "parent"), name="unique_slug_per_parent"
            ),
        ),
    ]
